language: go
go: 1.14.x
services:
  - docker

before_script:
  - sudo curl -fsSL https://goss.rocks/install | sudo sh
  - go get -u golang.org/x/lint/golint

script:
  - golint .
  - docker build --file build/Containerfile --tag gcp-gce-exporter:testing .
  - GOSS_FILES_PATH=test dgoss run gcp-gce-exporter:testing
